_wandb:
    value:
        cli_version: 0.21.4
        e:
            m9e9d1b3vjonbbyu7d4kzma54p498wzn:
                args:
                    - --parameter_config
                    - /content/drive/MyDrive/my_projects/trained_models_2.0/universal_layer_removed_augmentation_test_gpu/config.toml
                cpu_count: 1
                cpu_count_logical: 2
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "120942624768"
                        used: "42473938944"
                email: gertrude.zahra-bianco.16@um.edu.mt
                executable: /usr/bin/python3
                git:
                    commit: e87c42f12173b4fdb43ec2928c05dafab2f149c0
                    remote: https://gerry019:@github.com/gerry019/GelGenie.git
                gpu: Tesla T4
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-2d0cae9d-63be-8eba-4579-cc26c063b011
                host: 35c9a85c5138
                memory:
                    total: "13605658624"
                os: Linux-6.6.97+-x86_64-with-glibc2.35
                program: /usr/local/bin/gelseg_train
                python: CPython 3.12.11
                root: /content/drive/MyDrive/my_projects/GelGenie-fork/python-gelgenie
                startedAt: "2025-10-03T07:50:21.945806Z"
                writerId: m9e9d1b3vjonbbyu7d4kzma54p498wzn
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
                - 41
                - 49
                - 80
                - 105
            "2":
                - 1
                - 41
                - 49
                - 63
                - 74
                - 80
                - 105
            "3":
                - 2
                - 13
                - 14
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
